* Change Log
All notable changes to this project will be documented in this file. This change log follows the conventions of [keepachangelog.com](http://keepachangelog.com/).

** Unreleased
*** Fixed
- can't read already defined :layers in :layers pre-defination

[Unreleased]: https://github.com/yqrashawn/GokuRakuJoudo/compare/v0.1.14...HEAD

** 1.14 - 2018-12-22
*** Added
- add :sim in <other options> :params, [[https://github.com/yqrashawn/GokuRakuJoudo/blob/b9b334a187379f9bc8182ad59e2cca2a1789e9c0/src/karabiner_configurator/rules.clj#L183][params spec]]

*** Fixed
- error when running with brew service caused by new version of joker (v0.10.2)

[0.1.14]: https://github.com/yqrashawn/GokuRakuJoudo/compare/v0.1.13...v0.1.14

** 1.13 - 2018-12-07
*** Added
- add command to open log file
- use [[https://github.com/candid82/joker][joker]] to check edn file syntax, (add joker as dependency via homebrew)

[0.1.13]: https://github.com/yqrashawn/GokuRakuJoudo/compare/v0.1.12...v0.1.13

** 1.12 - 2018-12-07
*** Added
- error message when goku can't find the "Goku" profile
- now we support ~{:held <to defination>}~ ~{:dealyed {:invoked <to defination>} {:dealyed <to defination>}}~ in simlayer keys (not simlayer defination) #15

[0.1.12]: https://github.com/yqrashawn/GokuRakuJoudo/compare/v0.1.11...v0.1.12

** 1.11 - 2018-10-17
*** Fixed
- error while parsing ~{:any :key_code}~ as <from> section in rule
- more friendly error message, simply removed the stacktrace of the AssertionError

[0.1.11]: https://github.com/yqrashawn/GokuRakuJoudo/compare/v0.1.10...v0.1.11

** 1.10 - 2018-10-14
*** Fixed
- documentation typo, make readme more clear
*** Added
- now user can override ~to_if_alone~ when defining ~:layers~

[0.1.10]: https://github.com/yqrashawn/GokuRakuJoudo/compare/v0.1.9...v0.1.10

** 0.1.9 - 2018-10-02
*** Fixed
- different input source definition
now predefined input sources is ~:input-sources~ instead of ~:input_sources~
- fix homebrew service log file premission
now the brew service log file located at ~~/Library/Logs/goku.log~, contains
both stderr and stdout.

[0.1.9]: https://github.com/yqrashawn/GokuRakuJoudo/compare/v0.1.8...v0.1.9

** 0.1.8 - 2018-09-24
*** Added
- old ~:layers~ predefinition

#+begin_src clojure
;; before this feature
;; can only define "old" layers like this
{:main [{:des "w layer"
         :rules [[:w ["wlayer" 1] nil {:alone :w :afterup ["wlayer" 0]}]
                 [:e "open -a Emacs.app" :wlayer]
                 [:s "open -a Safari.app" :wlayer]]}]}

;; now we can do it with predefined layer
{:layers {:wlayer {:key :w}}
  :main [{:des "w layer"
          :rules [[:e "open -a Emacs.app" :wlayer]
                  [:s "open -a Safari.app" :wlayer]]}]}
#+end_src

- group rules by conditions

#+begin_src clojure
;; before this feature
;; we have to declare conditions in each rule, like this
{:layers {:wlayer {:key :w}
          :xlayer {:key :x}}
 :main [{:des "example layer"
         :rules [[:e "open -a Emacs.app" :wlayer]
                 [:s "open -a Safari.app" :wlayer]
                 [:i "open -a iTunes.app" :xlayer]]}]}

;; now we can group rules with conditions
{:applications {:chromes ["^com\\.google\\.Chrome$"
                          "^org\\.chromium\\.Chromium$"
                          "^com\\.google\\.Chrome\\.canary$"]}
 :layers {:wlayer {:key :w}
          :xlayer {:key :x}}
 :main [{:des "example layer"
         :rules [:wlayer
                 [:e "open -a Emacs.app"]
                 [:s "open -a Safari.app"]
                 :xlayer
                 [:i "open -a iTunes.app"]

                 ;; support multiple conditions
                 ;; use vector start with :condi for multiple conditions
                 [:condi :xlayer :chromes]
                 [:i "open -a iTunes.app"]

                 ;; you can still spercify conditions as the third element of the rule vector
                 ;; it will be combined with the group condition
                 ;; below rule is same as above one
                 :xlayer
                 [:i "open -a iTunes.app" :chromes]]}]}
#+end_src

[0.1.8]: https://github.com/yqrashawn/GokuRakuJoudo/compare/v0.1.7...v0.1.8

** 0.1.7 - 2018-09-19
*** Fixed
- use keyword defined in :input-sources to as <to> key

[0.1.7]: https://github.com/yqrashawn/GokuRakuJoudo/compare/v0.1.6...v0.1.7

** 0.1.6 - 2018-09-15
*** Fixed
- karabiner.json broken when can't find karabiner.edn
*** Added
- can install through brew now, ~brew install yqrashawn/goku/goku~
- ~gokuw~ as watch script, ~brew services start goku~ as service

[0.1.6]: https://github.com/yqrashawn/GokuRakuJoudo/compare/v0.1.3...v0.1.6

** 0.1.3 - 2018-09-11
*** Fixed
- seems the previous release version is not usable, the $HOME variable is always
  /Users/.travis, fixed that.

[0.1.3]: https://github.com/yqrashawn/GokuRakuJoudo/compare/v0.1.2...v0.1.3

** 0.1.2 - 2018-09-10
*** Fixed
- typo in rules, seems I spell all "cancel" wrong.

[0.1.2]: https://github.com/yqrashawn/GokuRakuJoudo/compare/v0.1.1...v0.1.2

** 0.1.1 - 2018-09-07
*** Added
- to key check while parsing key code
*** Changed
- ~:mission_control~ to normal key
*** Fixed
- karabiner error while using ~:mission_control~
- multiple devices condition bug

[0.1.1]: https://github.com/yqrashawn/GokuRakuJoudo/compare/v0.1.0...v0.1.1

** 0.1.0 - 2018-09-07
*** Added
- First release
